import { resolve } from 'node:path'
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import tailwindcss from '@tailwindcss/vite'
import { VitePWA } from 'vite-plugin-pwa'

// VitePWA + Workbox is the single biggest memory consumer in the build pipeline.
// Vercel's free/hobby tier gives ~4GB total — workbox alone can spike to 2GB+
// during precache manifest generation, on top of Rollup/Rolldown's own usage.
// Default to OFF on Vercel; flip ENABLE_PWA=true to opt back in (e.g. on Pro).
const PWA_ENABLED = process.env.ENABLE_PWA === 'true'

export default defineConfig({
  plugins: [
    react(),
    tailwindcss(),
    // When the real PWA plugin isn't loaded, stub `virtual:pwa-register` so
    // `src/lib/pwa.ts` still bundles — without this, Rolldown fails to
    // resolve the import and the whole build errors out.
    ...(!PWA_ENABLED ? [{
      name: 'kairo-pwa-register-stub',
      resolveId(id: string) {
        if (id === 'virtual:pwa-register') return '\0virtual:pwa-register'
        return null
      },
      load(id: string) {
        if (id === '\0virtual:pwa-register') {
          return `export function registerSW(_options) { return (_reload) => {} }`
        }
        return null
      },
    }] : []),
    ...(PWA_ENABLED ? [VitePWA({
      // 'autoUpdate' — the service worker updates silently in the background and
      // the new build applies on the next reload/relaunch. (We tried 'prompt' +
      // an auto-reload splash, but a stuck/looping SW state could trap the app on
      // the "Updating…" screen, so we reverted to the safe silent update.)
      registerType: 'autoUpdate',
      includeAssets: ['kairo_logo.png', 'favicon.svg', 'apple-touch-icon.png'],
      manifest: {
        name:             'Kyno',
        short_name:       'Kyno',
        description:      'Kyno is an AI-powered education platform by Kairo Industries.',
        // Match the rest of Kairo — deep purple accent on pure black.
        // Both theme + background are dark so the install/launch flow on
        // Android no longer flashes white at any point.
        theme_color:      '#0B0B14',   // matches <meta name="theme-color"> and public/manifest.webmanifest
        background_color: '#0B0B14',
        display:          'standalone',
        orientation:      'portrait',
        scope:            '/',
        start_url:        '/',
        categories:       ['education', 'productivity'],
        icons: [
          // Pre-baked Apple-squircle icons (dark background + glow + mark).
          // Generated by tools/make_kairo_icons.py.
          { src: '/kairo_icon_192.png',          sizes: '192x192', type: 'image/png', purpose: 'any' },
          { src: '/kairo_icon_512.png',          sizes: '512x512', type: 'image/png', purpose: 'any' },
          { src: '/kairo_icon_512_maskable.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
          // Legacy fallback so old caches still resolve.
          { src: '/kairo_logo.png',              sizes: '192x192', type: 'image/png', purpose: 'any' },
        ],
      },
      workbox: {
        globPatterns: ['**/*.{js,css,html,svg,png,ico,woff2}'],
        // Don't PRECACHE the giant lazy-route vendors (3D labs ~1.3MB, markdown
        // ~0.4MB). Precaching them made the service worker pull ~1.7MB in the
        // background on first visit, which is exactly what lazy-loading them was
        // meant to avoid. They're runtime-cached below after first real use.
        globIgnores: [
          '**/models/**', '**/*.glb',
          '**/assets/r3f-*.js', '**/assets/three-*.js', '**/assets/markdown-*.js',
        ],
        maximumFileSizeToCacheInBytes: 5 * 1024 * 1024,
        navigateFallbackDenylist: [/^\/api/],
        runtimeCaching: [
          {
            // The heavy lazy chunks we deliberately excluded from precache:
            // cache them the first time they're actually needed, then serve local.
            urlPattern: /\/assets\/(r3f|three|markdown)-[A-Za-z0-9_-]+\.js$/,
            handler: 'CacheFirst',
            options: {
              cacheName: 'kyno-heavy-chunks',
              expiration: { maxEntries: 12, maxAgeSeconds: 60 * 60 * 24 * 30 },
              cacheableResponse: { statuses: [0, 200] },
            },
          },
          {
            urlPattern: /^https:\/\/fonts\.(?:googleapis|gstatic)\.com\/.*/i,
            handler: 'CacheFirst',
            options: {
              cacheName: 'kairo-fonts',
              expiration: { maxEntries: 30, maxAgeSeconds: 60 * 60 * 24 * 365 },
              cacheableResponse: { statuses: [0, 200] },
            },
          },
          {
            urlPattern: /^https:\/\/cdn\.jsdelivr\.net\/.*/i,
            handler: 'CacheFirst',
            options: {
              cacheName: 'kairo-cdn',
              expiration: { maxEntries: 30, maxAgeSeconds: 60 * 60 * 24 * 30 },
            },
          },
          {
            urlPattern: /\/api\//,
            handler: 'NetworkOnly',
          },
        ],
      },
      devOptions: { enabled: false },
    })] : []),
  ],
  // The version string at the bottom of Profile: package.json's version plus
  // the short commit Vercel built from (empty locally).
  define: {
    __APP_VERSION__: JSON.stringify(process.env.npm_package_version || '0.0.0'),
    __APP_BUILD__:   JSON.stringify((process.env.VERCEL_GIT_COMMIT_SHA || '').slice(0, 7)),
  },
  build: {
    chunkSizeWarningLimit: 1500,
    sourcemap: false,
    // These vendor chunks belong to lazily-loaded routes (3D labs, markdown
    // rendering). Without this they still get <link rel="modulepreload">'d and
    // downloaded on the login screen — ~1.7MB nobody needs yet. They still load
    // on demand when the lazy route that needs them is opened.
    modulePreload: {
      resolveDependencies: (_url: string, deps: string[]) =>
        deps.filter(d => !/\b(three|r3f|markdown)-[A-Za-z0-9_-]+\.js$/.test(d)),
    },
    // Aggressive code-splitting keeps Rolldown's per-chunk peak memory low.
    rollupOptions: {
      // The dev-only harness is built too, so the PRODUCTION bundle can be
      // driven without a login. Chunking only happens in a real build, which
      // is why the "Cannot access 'R' before initialization" crash could not
      // be reproduced against the dev server.
      input: {
        main: resolve(__dirname, 'index.html'),
        'dashboard-preview': resolve(__dirname, 'dashboard-preview.html'),
      },
      // temporarily on, to name a minified binding in a chunk-order crash
      output: {
        manualChunks: (id: string) => {
          // ONLY DEPENDENCIES. These are substring matches, so they happily
          // caught our own source too: src/lib/katex.ts matched the 'katex'
          // rule and was pulled into the markdown vendor chunk, away from the
          // components that use it. The result was a chunk-level cycle and a
          // "Cannot access 'R' before initialization" the moment a space tried
          // to render maths -- Doubt, Practice, Notes and Performance all died
          // on the error boundary. Our files belong with their callers.
          if (!id.includes('node_modules')) return undefined
          if (id.includes('node_modules/three/')) return 'three'
          if (id.includes('node_modules/@react-three/')) return 'r3f'
          if (
            id.includes('react-markdown') ||
            id.includes('remark-') ||
            id.includes('rehype-') ||
            id.includes('katex') ||
            id.includes('mdast') ||
            id.includes('hast') ||
            id.includes('micromark') ||
            id.includes('unist')
          ) return 'markdown'
          if (id.includes('framer-motion')) return 'motion'
          if (id.includes('@supabase/')) return 'supabase'
          if (id.includes('lucide-react')) return 'icons'
          return undefined
        },
      },
    },
  },
  server: {
    port: 3002,
    proxy: {
      '/api': {
        target: 'http://localhost:4000',
        changeOrigin: true,
      },
    },
  },
})
