import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import tailwindcss from '@tailwindcss/vite'
import { VitePWA } from 'vite-plugin-pwa'

// VitePWA + Workbox is the single biggest memory consumer in the build pipeline.
// Vercel's free/hobby tier gives ~4GB total — workbox alone can spike to 2GB+
// during precache manifest generation, on top of Rollup/Rolldown's own usage.
// Default to OFF on Vercel; flip ENABLE_PWA=true to opt back in (e.g. on Pro).
const PWA_ENABLED = process.env.ENABLE_PWA === 'true'

export default defineConfig({
  plugins: [
    react(),
    tailwindcss(),
    // When the real PWA plugin isn't loaded, stub `virtual:pwa-register` so
    // `src/lib/pwa.ts` still bundles — without this, Rolldown fails to
    // resolve the import and the whole build errors out.
    ...(!PWA_ENABLED ? [{
      name: 'kairo-pwa-register-stub',
      resolveId(id: string) {
        if (id === 'virtual:pwa-register') return '\0virtual:pwa-register'
        return null
      },
      load(id: string) {
        if (id === '\0virtual:pwa-register') {
          return `export function registerSW(_options) { return (_reload) => {} }`
        }
        return null
      },
    }] : []),
    ...(PWA_ENABLED ? [VitePWA({
      // 'prompt' (not 'autoUpdate') so onNeedRefresh fires when a new deploy is
      // ready — main.tsx shows the branded "Updating…" splash and reloads. With
      // autoUpdate an already-open PWA silently kept the old bundle, which is how
      // two devices ended up on different code (and different XP).
      registerType: 'prompt',
      includeAssets: ['kairo_logo.png', 'favicon.svg', 'apple-touch-icon.png'],
      manifest: {
        name:             'Kairo — Accelerate Your Academics',
        short_name:       'Kairo',
        description:      'AI-powered school operating system for Indian classrooms.',
        // Match the rest of Kairo — deep purple accent on pure black.
        // Both theme + background are dark so the install/launch flow on
        // Android no longer flashes white at any point.
        theme_color:      '#06060a',
        background_color: '#06060a',
        display:          'standalone',
        orientation:      'portrait',
        scope:            '/',
        start_url:        '/',
        categories:       ['education', 'productivity'],
        icons: [
          // Pre-baked Apple-squircle icons (dark background + glow + mark).
          // Generated by tools/make_kairo_icons.py.
          { src: '/kairo_icon_192.png',          sizes: '192x192', type: 'image/png', purpose: 'any' },
          { src: '/kairo_icon_512.png',          sizes: '512x512', type: 'image/png', purpose: 'any' },
          { src: '/kairo_icon_512_maskable.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
          // Legacy fallback so old caches still resolve.
          { src: '/kairo_logo.png',              sizes: '192x192', type: 'image/png', purpose: 'any' },
        ],
      },
      workbox: {
        globPatterns: ['**/*.{js,css,html,svg,png,ico,woff2}'],
        globIgnores: ['**/models/**', '**/*.glb'],
        maximumFileSizeToCacheInBytes: 5 * 1024 * 1024,
        navigateFallbackDenylist: [/^\/api/],
        runtimeCaching: [
          {
            urlPattern: /^https:\/\/fonts\.(?:googleapis|gstatic)\.com\/.*/i,
            handler: 'CacheFirst',
            options: {
              cacheName: 'kairo-fonts',
              expiration: { maxEntries: 30, maxAgeSeconds: 60 * 60 * 24 * 365 },
              cacheableResponse: { statuses: [0, 200] },
            },
          },
          {
            urlPattern: /^https:\/\/cdn\.jsdelivr\.net\/.*/i,
            handler: 'CacheFirst',
            options: {
              cacheName: 'kairo-cdn',
              expiration: { maxEntries: 30, maxAgeSeconds: 60 * 60 * 24 * 30 },
            },
          },
          {
            urlPattern: /\/api\//,
            handler: 'NetworkOnly',
          },
        ],
      },
      devOptions: { enabled: false },
    })] : []),
  ],
  build: {
    chunkSizeWarningLimit: 1500,
    sourcemap: false,
    // Aggressive code-splitting keeps Rolldown's per-chunk peak memory low.
    rollupOptions: {
      output: {
        manualChunks: (id: string) => {
          if (id.includes('node_modules/three/')) return 'three'
          if (id.includes('node_modules/@react-three/')) return 'r3f'
          if (
            id.includes('react-markdown') ||
            id.includes('remark-') ||
            id.includes('rehype-') ||
            id.includes('katex') ||
            id.includes('mdast') ||
            id.includes('hast') ||
            id.includes('micromark') ||
            id.includes('unist')
          ) return 'markdown'
          if (id.includes('framer-motion')) return 'motion'
          if (id.includes('@supabase/')) return 'supabase'
          if (id.includes('lucide-react')) return 'icons'
          return undefined
        },
      },
    },
  },
  server: {
    port: 3002,
    proxy: {
      '/api': {
        target: 'http://localhost:4000',
        changeOrigin: true,
      },
    },
  },
})
